label: Trackbacks
version: 1.0
schema_version: 1.0

object_types:
    tbping: MT::TBPing
    ping: MT::TBPing
    ping_cat: MT::TBPing
    log.ping: MT::Log::TBPing
    trackback: MT::Trackback
    
config_settings:
    WeblogsPingURL:
        default: http://rpc.weblogs.com/RPC2
    BlogsPingURL:
        default: http://ping.blo.gs/
    MTPingURL:
        default: http://www.movabletype.org/update/
    TechnoratiPingURL:
        default: http://rpc.technorati.com/rpc/ping
    GooglePingURL:
        default: http://blogsearch.google.com/ping/RPC2
    PingTimeout:
        default: 60
    PingInterface: ~
    PingProxy: ~
    PingNoProxy:
        default: localhost
    OneHourMaxPings:
        default: 10
    OneDayMaxPings: 
        default: 50
    AllowPings:
        default: 1
    DisableNotificationPings:
        default: 0
    
ping_servers:
    weblogs:
        label: weblogs.com,
        url: http://rpc.weblogs.com/RPC2
    technorati:
        label: technorati.com
        url: http://rpc.technorati.com/rpc/ping
    google:
        label: google.com
        url: http://blogsearch.google.com/ping/RPC2

