id: Trackback
label: Trackbacks
version: 1.0
schema_version: 1.0

object_types:
    tbping: MT::TBPing
    ping: MT::TBPing
    ping_cat: MT::TBPing
    log.ping: MT::Log::TBPing
    trackback: MT::Trackback
    
config_settings:
    OneHourMaxPings:
        default: 10
    OneDayMaxPings: 
        default: 50
    AllowPings:
        default: 1
    DisableNotificationPings:
        default: 0
    
applications:
    tb:
        handler: MT::App::Trackback

    cms:
        methods:
            list_ping: $Trackback::MT::CMS::TrackBack::list
            cfg_trackbacks: $Trackback::MT::CMS::TrackBack::cfg_trackbacks
            
            ## DEPRECATED
            list_pings: $Trackback::MT::CMS::TrackBack::list
            
        list_actions:
            ping:
                unapprove_ping:
                    label: Unpublish TrackBack(s)
                    order: 100
                    code: $Trackback::MT::CMS::Comment::unapprove_item
                    permission: edit_all_posts,manage_feedback,publish_post

        list_filters:
            ping:
                default:
                    label: Non-spam TrackBacks
                    order: 100
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            require MT::TBPing;
                            $terms->{junk_status} = MT::TBPing::NOT_JUNK();
                        }                        
                my_posts:
                    label: TrackBacks on my entries
                    order: 200
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            require MT::Entry;
                            my $app = MT->instance;
                            require MT::TBPing;
                            require MT::Trackback;
                            $terms->{junk_status} = MT::TBPing::NOT_JUNK();
                            $args->{join}         = MT::Trackback->join_on(
                                undef,
                                { id => \'= tbping_tb_id', },
                                {   join => MT::Entry->join_on(
                                        undef,
                                        {   id        => \'= trackback_entry_id',
                                            author_id => $app->user->id
                                        }
                                    )
                                },
                            );
                        }
                published:
                    label: Published TrackBacks
                    order: 200
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            $terms->{visible} = 1;
                        }
                unpublished:
                    label: Unpublished TrackBacks
                    order: 300
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            require MT::TBPing;
                            $terms->{junk_status} = MT::TBPing::NOT_JUNK();
                            $terms->{visible}     = 0;
                        }
                spam:
                    label: TrackBacks marked as Spam
                    order: 400
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            require MT::TBPing;
                            $terms->{junk_status} = MT::TBPing::JUNK();
                        }
                last_7_days:
                    label: All TrackBacks in the last 7 days
                    order: 700
                    handler: >
                        sub {
                            my ( $terms, $args ) = @_;
                            my $ts = time - 7 * 24 * 60 * 60;
                            $ts = epoch2ts( MT->app->blog, $ts );
                            $terms->{created_on} = [ $ts, undef ];
                            $args->{range_incl}{created_on} = 1;
                            $terms->{junk_status} = MT::TBPing::NOT_JUNK();
                        }

        menus:
            manage:ping:
                label: TrackBacks
                mode: list_pings
                order: 5000
                permission: create_post,edit_all_posts,manage_feedback
                
        callbacks:
            init_app: $Trackback::MT::CMS::TrackBack::init_app
            cms_edit.ping: $Trackback::MT::CMS::TrackBack::edit
            cms_view_permission_filter.ping: $Trackback::MT::CMS::TrackBack::can_view
            cms_save_permission_filter.ping: $Trackback::MT::CMS::TrackBack::can_save
            cms_delete_permission_filter.ping: $Trackback::MT::CMS::TrackBack::can_delete
            cms_pre_save.ping: $Trackback::MT::CMS::TrackBack::pre_save
            cms_post_save.ping: $Trackback::MT::CMS::TrackBack::post_save
            cms_post_delete.ping: $Trackback::MT::CMS::TrackBack::post_delete

callbacks:
    ActivityFeed.ping: $Trackback::MT::Trackback::ActivityFeeds::_feed_ping
    
tags:
    block:
        PingsHeader: $Core::MT::Template::Context::_hdlr_pass_tokens
        PingsFooter: $Core::MT::Template::Context::_hdlr_pass_tokens
        CategoryIfAllowPings?: $Trackback::MT::Template::Tags::Ping::_hdlr_category_allow_pings
        Pings: $Trackback::MT::Template::Tags::Ping::_hdlr_pings
        PingsSent: $Trackback::MT::Template::Tags::Ping::_hdlr_pings_sent
        PingEntry: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_entry
        IfPingsAllowed?: $Trackback::MT::Template::Tags::Ping::_hdlr_if_pings_allowed
        IfPingsAccepted?: $Trackback::MT::Template::Tags::Ping::_hdlr_if_pings_accepted
        IfPingsActive?: $Trackback::MT::Template::Tags::Ping::_hdlr_if_pings_active
        IfPingsModerated?: $Trackback::MT::Template::Tags::Ping::_hdlr_if_pings_moderated
        EntryIfAllowPings?: $Trackback::MT::Template::Tags::Ping::_hdlr_entry_if_allow_pings
    function:
        TrackbackScript: $Trackback::MT::Template::Tags::Ping_hdlr_trackback_script
        BlogPingCount: $Trackback::MT::Template::Tags::Ping::_hdlr_blog_ping_count
        EntryTrackbackCount: $Trackback::MT::Template::Tags::Ping::_hdlr_entry_ping_count
        EntryTrackbackLink: $Trackback::MT::Template::Tags::Ping::_hdlr_entry_tb_link
        EntryTrackbackData: $Trackback::MT::Template::Tags::Ping::_hdlr_entry_tb_data
        EntryTrackbackID: $Trackback::MT::Template::Tags::Ping::_hdlr_entry_tb_id
        PingsSentURL: $Trackback::MT::Template::Tags::Ping::_hdlr_pings_sent_url
        PingTitle: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_title
        PingID: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_id
        PingURL: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_url
        PingExcerpt: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_excerpt
        PingBlogName: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_blog_name
        PingIP: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_ip
        PingDate: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_date
        PingScore: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_score
        PingScoreHigh: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_score_high
        PingScoreLow: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_score_low
        PingScoreAvg: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_score_avg
        PingScoreCount: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_score_count
        PingRank: $Trackback::MT::Template::Tags::Ping::_hdlr_ping_rank
        CategoryTrackbackLink: $Trackback::MT::Template::Tags::Ping_hdlr_category_tb_link
        CategoryTrackbackCount: $Trackback::MT::Template::Tags::Ping_hdlr_category_tb_count

backup_instructions:
    # Ping should be backed up after Trackback.
    trackback:
        order: 510
    tbping:
        order: 520
    ping:
        order: 520
    ping_cat:
        order: 520
